/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.information_schema.tables.records;


import burst.pool.migrator.nogroddb.information_schema.tables.InnodbSysSemaphoreWaits;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbSysSemaphoreWaitsRecord extends TableRecordImpl<InnodbSysSemaphoreWaitsRecord> implements Record20<ULong, String, String, UInteger, ULong, ULong, String, ULong, String, UInteger, String, UInteger, ULong, String, UInteger, ULong, ULong, String, UInteger, UInteger> {

    private static final long serialVersionUID = 775893441;

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.THREAD_ID</code>.
     */
    public void setThreadId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.THREAD_ID</code>.
     */
    public ULong getThreadId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.OBJECT_NAME</code>.
     */
    public void setObjectName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.OBJECT_NAME</code>.
     */
    public String getObjectName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.FILE</code>.
     */
    public void setFile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.FILE</code>.
     */
    public String getFile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LINE</code>.
     */
    public void setLine(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LINE</code>.
     */
    public UInteger getLine() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TIME</code>.
     */
    public void setWaitTime(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TIME</code>.
     */
    public ULong getWaitTime() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_OBJECT</code>.
     */
    public void setWaitObject(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_OBJECT</code>.
     */
    public ULong getWaitObject() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TYPE</code>.
     */
    public void setWaitType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TYPE</code>.
     */
    public String getWaitType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_THREAD_ID</code>.
     */
    public void setHolderThreadId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_THREAD_ID</code>.
     */
    public ULong getHolderThreadId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_FILE</code>.
     */
    public void setHolderFile(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_FILE</code>.
     */
    public String getHolderFile() {
        return (String) get(8);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_LINE</code>.
     */
    public void setHolderLine(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_LINE</code>.
     */
    public UInteger getHolderLine() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.CREATED_FILE</code>.
     */
    public void setCreatedFile(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.CREATED_FILE</code>.
     */
    public String getCreatedFile() {
        return (String) get(10);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.CREATED_LINE</code>.
     */
    public void setCreatedLine(UInteger value) {
        set(11, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.CREATED_LINE</code>.
     */
    public UInteger getCreatedLine() {
        return (UInteger) get(11);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WRITER_THREAD</code>.
     */
    public void setWriterThread(ULong value) {
        set(12, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WRITER_THREAD</code>.
     */
    public ULong getWriterThread() {
        return (ULong) get(12);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.RESERVATION_MODE</code>.
     */
    public void setReservationMode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.RESERVATION_MODE</code>.
     */
    public String getReservationMode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.READERS</code>.
     */
    public void setReaders(UInteger value) {
        set(14, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.READERS</code>.
     */
    public UInteger getReaders() {
        return (UInteger) get(14);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAITERS_FLAG</code>.
     */
    public void setWaitersFlag(ULong value) {
        set(15, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.WAITERS_FLAG</code>.
     */
    public ULong getWaitersFlag() {
        return (ULong) get(15);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LOCK_WORD</code>.
     */
    public void setLockWord(ULong value) {
        set(16, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LOCK_WORD</code>.
     */
    public ULong getLockWord() {
        return (ULong) get(16);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_FILE</code>.
     */
    public void setLastWriterFile(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_FILE</code>.
     */
    public String getLastWriterFile() {
        return (String) get(17);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_LINE</code>.
     */
    public void setLastWriterLine(UInteger value) {
        set(18, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_LINE</code>.
     */
    public UInteger getLastWriterLine() {
        return (UInteger) get(18);
    }

    /**
     * Setter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.OS_WAIT_COUNT</code>.
     */
    public void setOsWaitCount(UInteger value) {
        set(19, value);
    }

    /**
     * Getter for <code>information_schema.INNODB_SYS_SEMAPHORE_WAITS.OS_WAIT_COUNT</code>.
     */
    public UInteger getOsWaitCount() {
        return (UInteger) get(19);
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<ULong, String, String, UInteger, ULong, ULong, String, ULong, String, UInteger, String, UInteger, ULong, String, UInteger, ULong, ULong, String, UInteger, UInteger> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<ULong, String, String, UInteger, ULong, ULong, String, ULong, String, UInteger, String, UInteger, ULong, String, UInteger, ULong, ULong, String, UInteger, UInteger> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.THREAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.OBJECT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field6() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.WAIT_OBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.WAIT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field8() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_THREAD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field10() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.HOLDER_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.CREATED_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field12() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.CREATED_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field13() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.WRITER_THREAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.RESERVATION_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field15() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.READERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field16() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.WAITERS_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field17() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.LOCK_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field19() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.LAST_WRITER_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field20() {
        return InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS.OS_WAIT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getObjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component5() {
        return getWaitTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component6() {
        return getWaitObject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWaitType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component8() {
        return getHolderThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getHolderFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component10() {
        return getHolderLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreatedFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component12() {
        return getCreatedLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component13() {
        return getWriterThread();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getReservationMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component15() {
        return getReaders();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component16() {
        return getWaitersFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component17() {
        return getLockWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getLastWriterFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component19() {
        return getLastWriterLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component20() {
        return getOsWaitCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getObjectName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getWaitTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value6() {
        return getWaitObject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWaitType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value8() {
        return getHolderThreadId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getHolderFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value10() {
        return getHolderLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreatedFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value12() {
        return getCreatedLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value13() {
        return getWriterThread();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getReservationMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value15() {
        return getReaders();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value16() {
        return getWaitersFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value17() {
        return getLockWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getLastWriterFile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value19() {
        return getLastWriterLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value20() {
        return getOsWaitCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value1(ULong value) {
        setThreadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value2(String value) {
        setObjectName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value3(String value) {
        setFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value4(UInteger value) {
        setLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value5(ULong value) {
        setWaitTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value6(ULong value) {
        setWaitObject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value7(String value) {
        setWaitType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value8(ULong value) {
        setHolderThreadId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value9(String value) {
        setHolderFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value10(UInteger value) {
        setHolderLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value11(String value) {
        setCreatedFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value12(UInteger value) {
        setCreatedLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value13(ULong value) {
        setWriterThread(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value14(String value) {
        setReservationMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value15(UInteger value) {
        setReaders(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value16(ULong value) {
        setWaitersFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value17(ULong value) {
        setLockWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value18(String value) {
        setLastWriterFile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value19(UInteger value) {
        setLastWriterLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord value20(UInteger value) {
        setOsWaitCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbSysSemaphoreWaitsRecord values(ULong value1, String value2, String value3, UInteger value4, ULong value5, ULong value6, String value7, ULong value8, String value9, UInteger value10, String value11, UInteger value12, ULong value13, String value14, UInteger value15, ULong value16, ULong value17, String value18, UInteger value19, UInteger value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InnodbSysSemaphoreWaitsRecord
     */
    public InnodbSysSemaphoreWaitsRecord() {
        super(InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS);
    }

    /**
     * Create a detached, initialised InnodbSysSemaphoreWaitsRecord
     */
    public InnodbSysSemaphoreWaitsRecord(ULong threadId, String objectName, String file, UInteger line, ULong waitTime, ULong waitObject, String waitType, ULong holderThreadId, String holderFile, UInteger holderLine, String createdFile, UInteger createdLine, ULong writerThread, String reservationMode, UInteger readers, ULong waitersFlag, ULong lockWord, String lastWriterFile, UInteger lastWriterLine, UInteger osWaitCount) {
        super(InnodbSysSemaphoreWaits.INNODB_SYS_SEMAPHORE_WAITS);

        set(0, threadId);
        set(1, objectName);
        set(2, file);
        set(3, line);
        set(4, waitTime);
        set(5, waitObject);
        set(6, waitType);
        set(7, holderThreadId);
        set(8, holderFile);
        set(9, holderLine);
        set(10, createdFile);
        set(11, createdLine);
        set(12, writerThread);
        set(13, reservationMode);
        set(14, readers);
        set(15, waitersFlag);
        set(16, lockWord);
        set(17, lastWriterFile);
        set(18, lastWriterLine);
        set(19, osWaitCount);
    }
}
