/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.performance_schema.tables;


import burst.pool.migrator.nogroddb.performance_schema.PerformanceSchema;
import burst.pool.migrator.nogroddb.performance_schema.tables.records.EventsStagesSummaryGlobalByEventNameRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsStagesSummaryGlobalByEventName extends TableImpl<EventsStagesSummaryGlobalByEventNameRecord> {

    private static final long serialVersionUID = -1859051923;

    /**
     * The reference instance of <code>performance_schema.events_stages_summary_global_by_event_name</code>
     */
    public static final EventsStagesSummaryGlobalByEventName EVENTS_STAGES_SUMMARY_GLOBAL_BY_EVENT_NAME = new EventsStagesSummaryGlobalByEventName();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsStagesSummaryGlobalByEventNameRecord> getRecordType() {
        return EventsStagesSummaryGlobalByEventNameRecord.class;
    }

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.EVENT_NAME</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, String> EVENT_NAME = createField("EVENT_NAME", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.COUNT_STAR</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, ULong> COUNT_STAR = createField("COUNT_STAR", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.SUM_TIMER_WAIT</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, ULong> SUM_TIMER_WAIT = createField("SUM_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.MIN_TIMER_WAIT</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, ULong> MIN_TIMER_WAIT = createField("MIN_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.AVG_TIMER_WAIT</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, ULong> AVG_TIMER_WAIT = createField("AVG_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.events_stages_summary_global_by_event_name.MAX_TIMER_WAIT</code>.
     */
    public final TableField<EventsStagesSummaryGlobalByEventNameRecord, ULong> MAX_TIMER_WAIT = createField("MAX_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>performance_schema.events_stages_summary_global_by_event_name</code> table reference
     */
    public EventsStagesSummaryGlobalByEventName() {
        this(DSL.name("events_stages_summary_global_by_event_name"), null);
    }

    /**
     * Create an aliased <code>performance_schema.events_stages_summary_global_by_event_name</code> table reference
     */
    public EventsStagesSummaryGlobalByEventName(String alias) {
        this(DSL.name(alias), EVENTS_STAGES_SUMMARY_GLOBAL_BY_EVENT_NAME);
    }

    /**
     * Create an aliased <code>performance_schema.events_stages_summary_global_by_event_name</code> table reference
     */
    public EventsStagesSummaryGlobalByEventName(Name alias) {
        this(alias, EVENTS_STAGES_SUMMARY_GLOBAL_BY_EVENT_NAME);
    }

    private EventsStagesSummaryGlobalByEventName(Name alias, Table<EventsStagesSummaryGlobalByEventNameRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventsStagesSummaryGlobalByEventName(Name alias, Table<EventsStagesSummaryGlobalByEventNameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> EventsStagesSummaryGlobalByEventName(Table<O> child, ForeignKey<O, EventsStagesSummaryGlobalByEventNameRecord> key) {
        super(child, key, EVENTS_STAGES_SUMMARY_GLOBAL_BY_EVENT_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsStagesSummaryGlobalByEventName as(String alias) {
        return new EventsStagesSummaryGlobalByEventName(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsStagesSummaryGlobalByEventName as(Name alias) {
        return new EventsStagesSummaryGlobalByEventName(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventsStagesSummaryGlobalByEventName rename(String name) {
        return new EventsStagesSummaryGlobalByEventName(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventsStagesSummaryGlobalByEventName rename(Name name) {
        return new EventsStagesSummaryGlobalByEventName(name, null);
    }
}
