/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.performance_schema.tables;


import burst.pool.migrator.nogroddb.performance_schema.PerformanceSchema;
import burst.pool.migrator.nogroddb.performance_schema.tables.records.MutexInstancesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MutexInstances extends TableImpl<MutexInstancesRecord> {

    private static final long serialVersionUID = -918681890;

    /**
     * The reference instance of <code>performance_schema.mutex_instances</code>
     */
    public static final MutexInstances MUTEX_INSTANCES = new MutexInstances();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MutexInstancesRecord> getRecordType() {
        return MutexInstancesRecord.class;
    }

    /**
     * The column <code>performance_schema.mutex_instances.NAME</code>.
     */
    public final TableField<MutexInstancesRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>performance_schema.mutex_instances.OBJECT_INSTANCE_BEGIN</code>.
     */
    public final TableField<MutexInstancesRecord, ULong> OBJECT_INSTANCE_BEGIN = createField("OBJECT_INSTANCE_BEGIN", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.mutex_instances.LOCKED_BY_THREAD_ID</code>.
     */
    public final TableField<MutexInstancesRecord, ULong> LOCKED_BY_THREAD_ID = createField("LOCKED_BY_THREAD_ID", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * Create a <code>performance_schema.mutex_instances</code> table reference
     */
    public MutexInstances() {
        this(DSL.name("mutex_instances"), null);
    }

    /**
     * Create an aliased <code>performance_schema.mutex_instances</code> table reference
     */
    public MutexInstances(String alias) {
        this(DSL.name(alias), MUTEX_INSTANCES);
    }

    /**
     * Create an aliased <code>performance_schema.mutex_instances</code> table reference
     */
    public MutexInstances(Name alias) {
        this(alias, MUTEX_INSTANCES);
    }

    private MutexInstances(Name alias, Table<MutexInstancesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MutexInstances(Name alias, Table<MutexInstancesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> MutexInstances(Table<O> child, ForeignKey<O, MutexInstancesRecord> key) {
        super(child, key, MUTEX_INSTANCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutexInstances as(String alias) {
        return new MutexInstances(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MutexInstances as(Name alias) {
        return new MutexInstances(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MutexInstances rename(String name) {
        return new MutexInstances(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MutexInstances rename(Name name) {
        return new MutexInstances(name, null);
    }
}
