/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.performance_schema.tables;


import burst.pool.migrator.nogroddb.performance_schema.PerformanceSchema;
import burst.pool.migrator.nogroddb.performance_schema.tables.records.TableLockWaitsSummaryByTableRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableLockWaitsSummaryByTable extends TableImpl<TableLockWaitsSummaryByTableRecord> {

    private static final long serialVersionUID = 1683657416;

    /**
     * The reference instance of <code>performance_schema.table_lock_waits_summary_by_table</code>
     */
    public static final TableLockWaitsSummaryByTable TABLE_LOCK_WAITS_SUMMARY_BY_TABLE = new TableLockWaitsSummaryByTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TableLockWaitsSummaryByTableRecord> getRecordType() {
        return TableLockWaitsSummaryByTableRecord.class;
    }

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_TYPE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, String> OBJECT_TYPE = createField("OBJECT_TYPE", org.jooq.impl.SQLDataType.VARCHAR(64).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_SCHEMA</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, String> OBJECT_SCHEMA = createField("OBJECT_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR(64).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_NAME</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, String> OBJECT_NAME = createField("OBJECT_NAME", org.jooq.impl.SQLDataType.VARCHAR(64).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_STAR</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_STAR = createField("COUNT_STAR", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WAIT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WAIT = createField("SUM_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WAIT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WAIT = createField("MIN_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WAIT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WAIT = createField("AVG_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WAIT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WAIT = createField("MAX_TIMER_WAIT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ = createField("COUNT_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ = createField("SUM_TIMER_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ = createField("MIN_TIMER_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ = createField("AVG_TIMER_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ = createField("MAX_TIMER_READ", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE = createField("COUNT_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE = createField("SUM_TIMER_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE = createField("MIN_TIMER_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE = createField("AVG_TIMER_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE = createField("MAX_TIMER_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ_NORMAL = createField("COUNT_READ_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ_NORMAL = createField("SUM_TIMER_READ_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ_NORMAL = createField("MIN_TIMER_READ_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ_NORMAL = createField("AVG_TIMER_READ_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ_NORMAL = createField("MAX_TIMER_READ_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_WITH_SHARED_LOCKS</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ_WITH_SHARED_LOCKS = createField("COUNT_READ_WITH_SHARED_LOCKS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ_WITH_SHARED_LOCKS = createField("SUM_TIMER_READ_WITH_SHARED_LOCKS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ_WITH_SHARED_LOCKS = createField("MIN_TIMER_READ_WITH_SHARED_LOCKS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ_WITH_SHARED_LOCKS = createField("AVG_TIMER_READ_WITH_SHARED_LOCKS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ_WITH_SHARED_LOCKS = createField("MAX_TIMER_READ_WITH_SHARED_LOCKS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_HIGH_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ_HIGH_PRIORITY = createField("COUNT_READ_HIGH_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ_HIGH_PRIORITY = createField("SUM_TIMER_READ_HIGH_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ_HIGH_PRIORITY = createField("MIN_TIMER_READ_HIGH_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ_HIGH_PRIORITY = createField("AVG_TIMER_READ_HIGH_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ_HIGH_PRIORITY = createField("MAX_TIMER_READ_HIGH_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NO_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ_NO_INSERT = createField("COUNT_READ_NO_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NO_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ_NO_INSERT = createField("SUM_TIMER_READ_NO_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NO_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ_NO_INSERT = createField("MIN_TIMER_READ_NO_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NO_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ_NO_INSERT = createField("AVG_TIMER_READ_NO_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NO_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ_NO_INSERT = createField("MAX_TIMER_READ_NO_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_READ_EXTERNAL = createField("COUNT_READ_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_READ_EXTERNAL = createField("SUM_TIMER_READ_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_READ_EXTERNAL = createField("MIN_TIMER_READ_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_READ_EXTERNAL = createField("AVG_TIMER_READ_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_READ_EXTERNAL = createField("MAX_TIMER_READ_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_ALLOW_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_ALLOW_WRITE = createField("COUNT_WRITE_ALLOW_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_ALLOW_WRITE = createField("SUM_TIMER_WRITE_ALLOW_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_ALLOW_WRITE = createField("MIN_TIMER_WRITE_ALLOW_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_ALLOW_WRITE = createField("AVG_TIMER_WRITE_ALLOW_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_ALLOW_WRITE = createField("MAX_TIMER_WRITE_ALLOW_WRITE", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_CONCURRENT_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_CONCURRENT_INSERT = createField("COUNT_WRITE_CONCURRENT_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_CONCURRENT_INSERT = createField("SUM_TIMER_WRITE_CONCURRENT_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_CONCURRENT_INSERT = createField("MIN_TIMER_WRITE_CONCURRENT_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_CONCURRENT_INSERT = createField("AVG_TIMER_WRITE_CONCURRENT_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_CONCURRENT_INSERT = createField("MAX_TIMER_WRITE_CONCURRENT_INSERT", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_DELAYED</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_DELAYED = createField("COUNT_WRITE_DELAYED", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_DELAYED</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_DELAYED = createField("SUM_TIMER_WRITE_DELAYED", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_DELAYED</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_DELAYED = createField("MIN_TIMER_WRITE_DELAYED", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_DELAYED</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_DELAYED = createField("AVG_TIMER_WRITE_DELAYED", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_DELAYED</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_DELAYED = createField("MAX_TIMER_WRITE_DELAYED", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_LOW_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_LOW_PRIORITY = createField("COUNT_WRITE_LOW_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_LOW_PRIORITY = createField("SUM_TIMER_WRITE_LOW_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_LOW_PRIORITY = createField("MIN_TIMER_WRITE_LOW_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_LOW_PRIORITY = createField("AVG_TIMER_WRITE_LOW_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_LOW_PRIORITY = createField("MAX_TIMER_WRITE_LOW_PRIORITY", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_NORMAL = createField("COUNT_WRITE_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_NORMAL = createField("SUM_TIMER_WRITE_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_NORMAL = createField("MIN_TIMER_WRITE_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_NORMAL = createField("AVG_TIMER_WRITE_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_NORMAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_NORMAL = createField("MAX_TIMER_WRITE_NORMAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> COUNT_WRITE_EXTERNAL = createField("COUNT_WRITE_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> SUM_TIMER_WRITE_EXTERNAL = createField("SUM_TIMER_WRITE_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MIN_TIMER_WRITE_EXTERNAL = createField("MIN_TIMER_WRITE_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> AVG_TIMER_WRITE_EXTERNAL = createField("AVG_TIMER_WRITE_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_EXTERNAL</code>.
     */
    public final TableField<TableLockWaitsSummaryByTableRecord, ULong> MAX_TIMER_WRITE_EXTERNAL = createField("MAX_TIMER_WRITE_EXTERNAL", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>performance_schema.table_lock_waits_summary_by_table</code> table reference
     */
    public TableLockWaitsSummaryByTable() {
        this(DSL.name("table_lock_waits_summary_by_table"), null);
    }

    /**
     * Create an aliased <code>performance_schema.table_lock_waits_summary_by_table</code> table reference
     */
    public TableLockWaitsSummaryByTable(String alias) {
        this(DSL.name(alias), TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);
    }

    /**
     * Create an aliased <code>performance_schema.table_lock_waits_summary_by_table</code> table reference
     */
    public TableLockWaitsSummaryByTable(Name alias) {
        this(alias, TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);
    }

    private TableLockWaitsSummaryByTable(Name alias, Table<TableLockWaitsSummaryByTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private TableLockWaitsSummaryByTable(Name alias, Table<TableLockWaitsSummaryByTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TableLockWaitsSummaryByTable(Table<O> child, ForeignKey<O, TableLockWaitsSummaryByTableRecord> key) {
        super(child, key, TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableLockWaitsSummaryByTable as(String alias) {
        return new TableLockWaitsSummaryByTable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableLockWaitsSummaryByTable as(Name alias) {
        return new TableLockWaitsSummaryByTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TableLockWaitsSummaryByTable rename(String name) {
        return new TableLockWaitsSummaryByTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TableLockWaitsSummaryByTable rename(Name name) {
        return new TableLockWaitsSummaryByTable(name, null);
    }
}
