/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.mysql.tables;


import burst.pool.migrator.nogroddb.mysql.Indexes;
import burst.pool.migrator.nogroddb.mysql.Keys;
import burst.pool.migrator.nogroddb.mysql.Mysql;
import burst.pool.migrator.nogroddb.mysql.tables.records.GtidSlavePosRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * Replication slave GTID position
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GtidSlavePos extends TableImpl<GtidSlavePosRecord> {

    private static final long serialVersionUID = 2063514120;

    /**
     * The reference instance of <code>mysql.gtid_slave_pos</code>
     */
    public static final GtidSlavePos GTID_SLAVE_POS = new GtidSlavePos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GtidSlavePosRecord> getRecordType() {
        return GtidSlavePosRecord.class;
    }

    /**
     * The column <code>mysql.gtid_slave_pos.domain_id</code>.
     */
    public final TableField<GtidSlavePosRecord, UInteger> DOMAIN_ID = createField("domain_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>mysql.gtid_slave_pos.sub_id</code>.
     */
    public final TableField<GtidSlavePosRecord, ULong> SUB_ID = createField("sub_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>mysql.gtid_slave_pos.server_id</code>.
     */
    public final TableField<GtidSlavePosRecord, UInteger> SERVER_ID = createField("server_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>mysql.gtid_slave_pos.seq_no</code>.
     */
    public final TableField<GtidSlavePosRecord, ULong> SEQ_NO = createField("seq_no", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>mysql.gtid_slave_pos</code> table reference
     */
    public GtidSlavePos() {
        this(DSL.name("gtid_slave_pos"), null);
    }

    /**
     * Create an aliased <code>mysql.gtid_slave_pos</code> table reference
     */
    public GtidSlavePos(String alias) {
        this(DSL.name(alias), GTID_SLAVE_POS);
    }

    /**
     * Create an aliased <code>mysql.gtid_slave_pos</code> table reference
     */
    public GtidSlavePos(Name alias) {
        this(alias, GTID_SLAVE_POS);
    }

    private GtidSlavePos(Name alias, Table<GtidSlavePosRecord> aliased) {
        this(alias, aliased, null);
    }

    private GtidSlavePos(Name alias, Table<GtidSlavePosRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Replication slave GTID position"));
    }

    public <O extends Record> GtidSlavePos(Table<O> child, ForeignKey<O, GtidSlavePosRecord> key) {
        super(child, key, GTID_SLAVE_POS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mysql.MYSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GTID_SLAVE_POS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GtidSlavePosRecord> getPrimaryKey() {
        return Keys.KEY_GTID_SLAVE_POS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GtidSlavePosRecord>> getKeys() {
        return Arrays.<UniqueKey<GtidSlavePosRecord>>asList(Keys.KEY_GTID_SLAVE_POS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GtidSlavePos as(String alias) {
        return new GtidSlavePos(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GtidSlavePos as(Name alias) {
        return new GtidSlavePos(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GtidSlavePos rename(String name) {
        return new GtidSlavePos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GtidSlavePos rename(Name name) {
        return new GtidSlavePos(name, null);
    }
}
