/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.mysql.tables;


import burst.pool.migrator.nogroddb.mysql.Indexes;
import burst.pool.migrator.nogroddb.mysql.Keys;
import burst.pool.migrator.nogroddb.mysql.Mysql;
import burst.pool.migrator.nogroddb.mysql.tables.records.TimeZoneLeapSecondRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * Leap seconds information for time zones
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeZoneLeapSecond extends TableImpl<TimeZoneLeapSecondRecord> {

    private static final long serialVersionUID = -1673901676;

    /**
     * The reference instance of <code>mysql.time_zone_leap_second</code>
     */
    public static final TimeZoneLeapSecond TIME_ZONE_LEAP_SECOND = new TimeZoneLeapSecond();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TimeZoneLeapSecondRecord> getRecordType() {
        return TimeZoneLeapSecondRecord.class;
    }

    /**
     * The column <code>mysql.time_zone_leap_second.Transition_time</code>.
     */
    public final TableField<TimeZoneLeapSecondRecord, Long> TRANSITION_TIME = createField("Transition_time", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>mysql.time_zone_leap_second.Correction</code>.
     */
    public final TableField<TimeZoneLeapSecondRecord, Integer> CORRECTION = createField("Correction", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>mysql.time_zone_leap_second</code> table reference
     */
    public TimeZoneLeapSecond() {
        this(DSL.name("time_zone_leap_second"), null);
    }

    /**
     * Create an aliased <code>mysql.time_zone_leap_second</code> table reference
     */
    public TimeZoneLeapSecond(String alias) {
        this(DSL.name(alias), TIME_ZONE_LEAP_SECOND);
    }

    /**
     * Create an aliased <code>mysql.time_zone_leap_second</code> table reference
     */
    public TimeZoneLeapSecond(Name alias) {
        this(alias, TIME_ZONE_LEAP_SECOND);
    }

    private TimeZoneLeapSecond(Name alias, Table<TimeZoneLeapSecondRecord> aliased) {
        this(alias, aliased, null);
    }

    private TimeZoneLeapSecond(Name alias, Table<TimeZoneLeapSecondRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("Leap seconds information for time zones"));
    }

    public <O extends Record> TimeZoneLeapSecond(Table<O> child, ForeignKey<O, TimeZoneLeapSecondRecord> key) {
        super(child, key, TIME_ZONE_LEAP_SECOND);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Mysql.MYSQL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TIME_ZONE_LEAP_SECOND_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TimeZoneLeapSecondRecord> getPrimaryKey() {
        return Keys.KEY_TIME_ZONE_LEAP_SECOND_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TimeZoneLeapSecondRecord>> getKeys() {
        return Arrays.<UniqueKey<TimeZoneLeapSecondRecord>>asList(Keys.KEY_TIME_ZONE_LEAP_SECOND_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeZoneLeapSecond as(String alias) {
        return new TimeZoneLeapSecond(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeZoneLeapSecond as(Name alias) {
        return new TimeZoneLeapSecond(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeZoneLeapSecond rename(String name) {
        return new TimeZoneLeapSecond(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TimeZoneLeapSecond rename(Name name) {
        return new TimeZoneLeapSecond(name, null);
    }
}
