/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.performance_schema.tables.records;


import burst.pool.migrator.nogroddb.performance_schema.enums.SetupTimersTimerName;
import burst.pool.migrator.nogroddb.performance_schema.tables.SetupTimers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupTimersRecord extends TableRecordImpl<SetupTimersRecord> implements Record2<String, SetupTimersTimerName> {

    private static final long serialVersionUID = 50962962;

    /**
     * Setter for <code>performance_schema.setup_timers.NAME</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>performance_schema.setup_timers.NAME</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>performance_schema.setup_timers.TIMER_NAME</code>.
     */
    public void setTimerName(SetupTimersTimerName value) {
        set(1, value);
    }

    /**
     * Getter for <code>performance_schema.setup_timers.TIMER_NAME</code>.
     */
    public SetupTimersTimerName getTimerName() {
        return (SetupTimersTimerName) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, SetupTimersTimerName> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, SetupTimersTimerName> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SetupTimers.SETUP_TIMERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<SetupTimersTimerName> field2() {
        return SetupTimers.SETUP_TIMERS.TIMER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupTimersTimerName component2() {
        return getTimerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupTimersTimerName value2() {
        return getTimerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupTimersRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupTimersRecord value2(SetupTimersTimerName value) {
        setTimerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetupTimersRecord values(String value1, SetupTimersTimerName value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SetupTimersRecord
     */
    public SetupTimersRecord() {
        super(SetupTimers.SETUP_TIMERS);
    }

    /**
     * Create a detached, initialised SetupTimersRecord
     */
    public SetupTimersRecord(String name, SetupTimersTimerName timerName) {
        super(SetupTimers.SETUP_TIMERS);

        set(0, name);
        set(1, timerName);
    }
}
