/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.mysql.tables.records;


import burst.pool.migrator.nogroddb.mysql.enums.HostAlterPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostAlterRoutinePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostCreatePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostCreateRoutinePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostCreateTmpTablePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostCreateViewPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostDeletePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostDropPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostExecutePriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostGrantPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostIndexPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostInsertPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostLockTablesPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostReferencesPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostSelectPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostShowViewPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostTriggerPriv;
import burst.pool.migrator.nogroddb.mysql.enums.HostUpdatePriv;
import burst.pool.migrator.nogroddb.mysql.tables.Host;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Host privileges;  Merged with database privileges
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HostRecord extends UpdatableRecordImpl<HostRecord> implements Record20<String, String, HostSelectPriv, HostInsertPriv, HostUpdatePriv, HostDeletePriv, HostCreatePriv, HostDropPriv, HostGrantPriv, HostReferencesPriv, HostIndexPriv, HostAlterPriv, HostCreateTmpTablePriv, HostLockTablesPriv, HostCreateViewPriv, HostShowViewPriv, HostCreateRoutinePriv, HostAlterRoutinePriv, HostExecutePriv, HostTriggerPriv> {

    private static final long serialVersionUID = 1532035890;

    /**
     * Setter for <code>mysql.host.Host</code>.
     */
    public void setHost(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql.host.Host</code>.
     */
    public String getHost() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mysql.host.Db</code>.
     */
    public void setDb(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql.host.Db</code>.
     */
    public String getDb() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mysql.host.Select_priv</code>.
     */
    public void setSelectPriv(HostSelectPriv value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql.host.Select_priv</code>.
     */
    public HostSelectPriv getSelectPriv() {
        return (HostSelectPriv) get(2);
    }

    /**
     * Setter for <code>mysql.host.Insert_priv</code>.
     */
    public void setInsertPriv(HostInsertPriv value) {
        set(3, value);
    }

    /**
     * Getter for <code>mysql.host.Insert_priv</code>.
     */
    public HostInsertPriv getInsertPriv() {
        return (HostInsertPriv) get(3);
    }

    /**
     * Setter for <code>mysql.host.Update_priv</code>.
     */
    public void setUpdatePriv(HostUpdatePriv value) {
        set(4, value);
    }

    /**
     * Getter for <code>mysql.host.Update_priv</code>.
     */
    public HostUpdatePriv getUpdatePriv() {
        return (HostUpdatePriv) get(4);
    }

    /**
     * Setter for <code>mysql.host.Delete_priv</code>.
     */
    public void setDeletePriv(HostDeletePriv value) {
        set(5, value);
    }

    /**
     * Getter for <code>mysql.host.Delete_priv</code>.
     */
    public HostDeletePriv getDeletePriv() {
        return (HostDeletePriv) get(5);
    }

    /**
     * Setter for <code>mysql.host.Create_priv</code>.
     */
    public void setCreatePriv(HostCreatePriv value) {
        set(6, value);
    }

    /**
     * Getter for <code>mysql.host.Create_priv</code>.
     */
    public HostCreatePriv getCreatePriv() {
        return (HostCreatePriv) get(6);
    }

    /**
     * Setter for <code>mysql.host.Drop_priv</code>.
     */
    public void setDropPriv(HostDropPriv value) {
        set(7, value);
    }

    /**
     * Getter for <code>mysql.host.Drop_priv</code>.
     */
    public HostDropPriv getDropPriv() {
        return (HostDropPriv) get(7);
    }

    /**
     * Setter for <code>mysql.host.Grant_priv</code>.
     */
    public void setGrantPriv(HostGrantPriv value) {
        set(8, value);
    }

    /**
     * Getter for <code>mysql.host.Grant_priv</code>.
     */
    public HostGrantPriv getGrantPriv() {
        return (HostGrantPriv) get(8);
    }

    /**
     * Setter for <code>mysql.host.References_priv</code>.
     */
    public void setReferencesPriv(HostReferencesPriv value) {
        set(9, value);
    }

    /**
     * Getter for <code>mysql.host.References_priv</code>.
     */
    public HostReferencesPriv getReferencesPriv() {
        return (HostReferencesPriv) get(9);
    }

    /**
     * Setter for <code>mysql.host.Index_priv</code>.
     */
    public void setIndexPriv(HostIndexPriv value) {
        set(10, value);
    }

    /**
     * Getter for <code>mysql.host.Index_priv</code>.
     */
    public HostIndexPriv getIndexPriv() {
        return (HostIndexPriv) get(10);
    }

    /**
     * Setter for <code>mysql.host.Alter_priv</code>.
     */
    public void setAlterPriv(HostAlterPriv value) {
        set(11, value);
    }

    /**
     * Getter for <code>mysql.host.Alter_priv</code>.
     */
    public HostAlterPriv getAlterPriv() {
        return (HostAlterPriv) get(11);
    }

    /**
     * Setter for <code>mysql.host.Create_tmp_table_priv</code>.
     */
    public void setCreateTmpTablePriv(HostCreateTmpTablePriv value) {
        set(12, value);
    }

    /**
     * Getter for <code>mysql.host.Create_tmp_table_priv</code>.
     */
    public HostCreateTmpTablePriv getCreateTmpTablePriv() {
        return (HostCreateTmpTablePriv) get(12);
    }

    /**
     * Setter for <code>mysql.host.Lock_tables_priv</code>.
     */
    public void setLockTablesPriv(HostLockTablesPriv value) {
        set(13, value);
    }

    /**
     * Getter for <code>mysql.host.Lock_tables_priv</code>.
     */
    public HostLockTablesPriv getLockTablesPriv() {
        return (HostLockTablesPriv) get(13);
    }

    /**
     * Setter for <code>mysql.host.Create_view_priv</code>.
     */
    public void setCreateViewPriv(HostCreateViewPriv value) {
        set(14, value);
    }

    /**
     * Getter for <code>mysql.host.Create_view_priv</code>.
     */
    public HostCreateViewPriv getCreateViewPriv() {
        return (HostCreateViewPriv) get(14);
    }

    /**
     * Setter for <code>mysql.host.Show_view_priv</code>.
     */
    public void setShowViewPriv(HostShowViewPriv value) {
        set(15, value);
    }

    /**
     * Getter for <code>mysql.host.Show_view_priv</code>.
     */
    public HostShowViewPriv getShowViewPriv() {
        return (HostShowViewPriv) get(15);
    }

    /**
     * Setter for <code>mysql.host.Create_routine_priv</code>.
     */
    public void setCreateRoutinePriv(HostCreateRoutinePriv value) {
        set(16, value);
    }

    /**
     * Getter for <code>mysql.host.Create_routine_priv</code>.
     */
    public HostCreateRoutinePriv getCreateRoutinePriv() {
        return (HostCreateRoutinePriv) get(16);
    }

    /**
     * Setter for <code>mysql.host.Alter_routine_priv</code>.
     */
    public void setAlterRoutinePriv(HostAlterRoutinePriv value) {
        set(17, value);
    }

    /**
     * Getter for <code>mysql.host.Alter_routine_priv</code>.
     */
    public HostAlterRoutinePriv getAlterRoutinePriv() {
        return (HostAlterRoutinePriv) get(17);
    }

    /**
     * Setter for <code>mysql.host.Execute_priv</code>.
     */
    public void setExecutePriv(HostExecutePriv value) {
        set(18, value);
    }

    /**
     * Getter for <code>mysql.host.Execute_priv</code>.
     */
    public HostExecutePriv getExecutePriv() {
        return (HostExecutePriv) get(18);
    }

    /**
     * Setter for <code>mysql.host.Trigger_priv</code>.
     */
    public void setTriggerPriv(HostTriggerPriv value) {
        set(19, value);
    }

    /**
     * Getter for <code>mysql.host.Trigger_priv</code>.
     */
    public HostTriggerPriv getTriggerPriv() {
        return (HostTriggerPriv) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, HostSelectPriv, HostInsertPriv, HostUpdatePriv, HostDeletePriv, HostCreatePriv, HostDropPriv, HostGrantPriv, HostReferencesPriv, HostIndexPriv, HostAlterPriv, HostCreateTmpTablePriv, HostLockTablesPriv, HostCreateViewPriv, HostShowViewPriv, HostCreateRoutinePriv, HostAlterRoutinePriv, HostExecutePriv, HostTriggerPriv> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<String, String, HostSelectPriv, HostInsertPriv, HostUpdatePriv, HostDeletePriv, HostCreatePriv, HostDropPriv, HostGrantPriv, HostReferencesPriv, HostIndexPriv, HostAlterPriv, HostCreateTmpTablePriv, HostLockTablesPriv, HostCreateViewPriv, HostShowViewPriv, HostCreateRoutinePriv, HostAlterRoutinePriv, HostExecutePriv, HostTriggerPriv> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Host.HOST.HOST_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Host.HOST.DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostSelectPriv> field3() {
        return Host.HOST.SELECT_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostInsertPriv> field4() {
        return Host.HOST.INSERT_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostUpdatePriv> field5() {
        return Host.HOST.UPDATE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostDeletePriv> field6() {
        return Host.HOST.DELETE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostCreatePriv> field7() {
        return Host.HOST.CREATE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostDropPriv> field8() {
        return Host.HOST.DROP_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostGrantPriv> field9() {
        return Host.HOST.GRANT_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostReferencesPriv> field10() {
        return Host.HOST.REFERENCES_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostIndexPriv> field11() {
        return Host.HOST.INDEX_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostAlterPriv> field12() {
        return Host.HOST.ALTER_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostCreateTmpTablePriv> field13() {
        return Host.HOST.CREATE_TMP_TABLE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostLockTablesPriv> field14() {
        return Host.HOST.LOCK_TABLES_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostCreateViewPriv> field15() {
        return Host.HOST.CREATE_VIEW_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostShowViewPriv> field16() {
        return Host.HOST.SHOW_VIEW_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostCreateRoutinePriv> field17() {
        return Host.HOST.CREATE_ROUTINE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostAlterRoutinePriv> field18() {
        return Host.HOST.ALTER_ROUTINE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostExecutePriv> field19() {
        return Host.HOST.EXECUTE_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<HostTriggerPriv> field20() {
        return Host.HOST.TRIGGER_PRIV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSelectPriv component3() {
        return getSelectPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostInsertPriv component4() {
        return getInsertPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostUpdatePriv component5() {
        return getUpdatePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostDeletePriv component6() {
        return getDeletePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreatePriv component7() {
        return getCreatePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostDropPriv component8() {
        return getDropPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostGrantPriv component9() {
        return getGrantPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostReferencesPriv component10() {
        return getReferencesPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostIndexPriv component11() {
        return getIndexPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostAlterPriv component12() {
        return getAlterPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateTmpTablePriv component13() {
        return getCreateTmpTablePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostLockTablesPriv component14() {
        return getLockTablesPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateViewPriv component15() {
        return getCreateViewPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostShowViewPriv component16() {
        return getShowViewPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateRoutinePriv component17() {
        return getCreateRoutinePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostAlterRoutinePriv component18() {
        return getAlterRoutinePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostExecutePriv component19() {
        return getExecutePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostTriggerPriv component20() {
        return getTriggerPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getHost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostSelectPriv value3() {
        return getSelectPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostInsertPriv value4() {
        return getInsertPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostUpdatePriv value5() {
        return getUpdatePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostDeletePriv value6() {
        return getDeletePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreatePriv value7() {
        return getCreatePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostDropPriv value8() {
        return getDropPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostGrantPriv value9() {
        return getGrantPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostReferencesPriv value10() {
        return getReferencesPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostIndexPriv value11() {
        return getIndexPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostAlterPriv value12() {
        return getAlterPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateTmpTablePriv value13() {
        return getCreateTmpTablePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostLockTablesPriv value14() {
        return getLockTablesPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateViewPriv value15() {
        return getCreateViewPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostShowViewPriv value16() {
        return getShowViewPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostCreateRoutinePriv value17() {
        return getCreateRoutinePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostAlterRoutinePriv value18() {
        return getAlterRoutinePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostExecutePriv value19() {
        return getExecutePriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostTriggerPriv value20() {
        return getTriggerPriv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value1(String value) {
        setHost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value2(String value) {
        setDb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value3(HostSelectPriv value) {
        setSelectPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value4(HostInsertPriv value) {
        setInsertPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value5(HostUpdatePriv value) {
        setUpdatePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value6(HostDeletePriv value) {
        setDeletePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value7(HostCreatePriv value) {
        setCreatePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value8(HostDropPriv value) {
        setDropPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value9(HostGrantPriv value) {
        setGrantPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value10(HostReferencesPriv value) {
        setReferencesPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value11(HostIndexPriv value) {
        setIndexPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value12(HostAlterPriv value) {
        setAlterPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value13(HostCreateTmpTablePriv value) {
        setCreateTmpTablePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value14(HostLockTablesPriv value) {
        setLockTablesPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value15(HostCreateViewPriv value) {
        setCreateViewPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value16(HostShowViewPriv value) {
        setShowViewPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value17(HostCreateRoutinePriv value) {
        setCreateRoutinePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value18(HostAlterRoutinePriv value) {
        setAlterRoutinePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value19(HostExecutePriv value) {
        setExecutePriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord value20(HostTriggerPriv value) {
        setTriggerPriv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HostRecord values(String value1, String value2, HostSelectPriv value3, HostInsertPriv value4, HostUpdatePriv value5, HostDeletePriv value6, HostCreatePriv value7, HostDropPriv value8, HostGrantPriv value9, HostReferencesPriv value10, HostIndexPriv value11, HostAlterPriv value12, HostCreateTmpTablePriv value13, HostLockTablesPriv value14, HostCreateViewPriv value15, HostShowViewPriv value16, HostCreateRoutinePriv value17, HostAlterRoutinePriv value18, HostExecutePriv value19, HostTriggerPriv value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HostRecord
     */
    public HostRecord() {
        super(Host.HOST);
    }

    /**
     * Create a detached, initialised HostRecord
     */
    public HostRecord(String host, String db, HostSelectPriv selectPriv, HostInsertPriv insertPriv, HostUpdatePriv updatePriv, HostDeletePriv deletePriv, HostCreatePriv createPriv, HostDropPriv dropPriv, HostGrantPriv grantPriv, HostReferencesPriv referencesPriv, HostIndexPriv indexPriv, HostAlterPriv alterPriv, HostCreateTmpTablePriv createTmpTablePriv, HostLockTablesPriv lockTablesPriv, HostCreateViewPriv createViewPriv, HostShowViewPriv showViewPriv, HostCreateRoutinePriv createRoutinePriv, HostAlterRoutinePriv alterRoutinePriv, HostExecutePriv executePriv, HostTriggerPriv triggerPriv) {
        super(Host.HOST);

        set(0, host);
        set(1, db);
        set(2, selectPriv);
        set(3, insertPriv);
        set(4, updatePriv);
        set(5, deletePriv);
        set(6, createPriv);
        set(7, dropPriv);
        set(8, grantPriv);
        set(9, referencesPriv);
        set(10, indexPriv);
        set(11, alterPriv);
        set(12, createTmpTablePriv);
        set(13, lockTablesPriv);
        set(14, createViewPriv);
        set(15, showViewPriv);
        set(16, createRoutinePriv);
        set(17, alterRoutinePriv);
        set(18, executePriv);
        set(19, triggerPriv);
    }
}
