/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.mysql.tables.records;


import burst.pool.migrator.nogroddb.mysql.tables.IndexStats;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * Statistics on Indexes
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndexStatsRecord extends UpdatableRecordImpl<IndexStatsRecord> implements Record5<String, String, String, UInteger, BigDecimal> {

    private static final long serialVersionUID = 91541887;

    /**
     * Setter for <code>mysql.index_stats.db_name</code>.
     */
    public void setDbName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql.index_stats.db_name</code>.
     */
    public String getDbName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mysql.index_stats.table_name</code>.
     */
    public void setTableName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql.index_stats.table_name</code>.
     */
    public String getTableName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mysql.index_stats.index_name</code>.
     */
    public void setIndexName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql.index_stats.index_name</code>.
     */
    public String getIndexName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mysql.index_stats.prefix_arity</code>.
     */
    public void setPrefixArity(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>mysql.index_stats.prefix_arity</code>.
     */
    public UInteger getPrefixArity() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>mysql.index_stats.avg_frequency</code>.
     */
    public void setAvgFrequency(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>mysql.index_stats.avg_frequency</code>.
     */
    public BigDecimal getAvgFrequency() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record4<String, String, String, UInteger> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, UInteger, BigDecimal> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, UInteger, BigDecimal> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return IndexStats.INDEX_STATS.DB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return IndexStats.INDEX_STATS.TABLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return IndexStats.INDEX_STATS.INDEX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return IndexStats.INDEX_STATS.PREFIX_ARITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return IndexStats.INDEX_STATS.AVG_FREQUENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDbName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component4() {
        return getPrefixArity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getAvgFrequency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDbName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getPrefixArity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getAvgFrequency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord value1(String value) {
        setDbName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord value2(String value) {
        setTableName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord value3(String value) {
        setIndexName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord value4(UInteger value) {
        setPrefixArity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord value5(BigDecimal value) {
        setAvgFrequency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndexStatsRecord values(String value1, String value2, String value3, UInteger value4, BigDecimal value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndexStatsRecord
     */
    public IndexStatsRecord() {
        super(IndexStats.INDEX_STATS);
    }

    /**
     * Create a detached, initialised IndexStatsRecord
     */
    public IndexStatsRecord(String dbName, String tableName, String indexName, UInteger prefixArity, BigDecimal avgFrequency) {
        super(IndexStats.INDEX_STATS);

        set(0, dbName);
        set(1, tableName);
        set(2, indexName);
        set(3, prefixArity);
        set(4, avgFrequency);
    }
}
