/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.mysql.tables.records;


import burst.pool.migrator.nogroddb.mysql.tables.TableStats;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * Statistics on Tables
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableStatsRecord extends UpdatableRecordImpl<TableStatsRecord> implements Record3<String, String, ULong> {

    private static final long serialVersionUID = 582616022;

    /**
     * Setter for <code>mysql.table_stats.db_name</code>.
     */
    public void setDbName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mysql.table_stats.db_name</code>.
     */
    public String getDbName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mysql.table_stats.table_name</code>.
     */
    public void setTableName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mysql.table_stats.table_name</code>.
     */
    public String getTableName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mysql.table_stats.cardinality</code>.
     */
    public void setCardinality(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>mysql.table_stats.cardinality</code>.
     */
    public ULong getCardinality() {
        return (ULong) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, ULong> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, ULong> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TableStats.TABLE_STATS.DB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TableStats.TABLE_STATS.TABLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return TableStats.TABLE_STATS.CARDINALITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getDbName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getCardinality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDbName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTableName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getCardinality();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableStatsRecord value1(String value) {
        setDbName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableStatsRecord value2(String value) {
        setTableName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableStatsRecord value3(ULong value) {
        setCardinality(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableStatsRecord values(String value1, String value2, ULong value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableStatsRecord
     */
    public TableStatsRecord() {
        super(TableStats.TABLE_STATS);
    }

    /**
     * Create a detached, initialised TableStatsRecord
     */
    public TableStatsRecord(String dbName, String tableName, ULong cardinality) {
        super(TableStats.TABLE_STATS);

        set(0, dbName);
        set(1, tableName);
        set(2, cardinality);
    }
}
