/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb;


import burst.pool.migrator.nogroddb.tables.Account;
import burst.pool.migrator.nogroddb.tables.Block;
import burst.pool.migrator.nogroddb.tables.Miner;
import burst.pool.migrator.nogroddb.tables.NonceSubmission;
import burst.pool.migrator.nogroddb.tables.SchemaMigrations;
import burst.pool.migrator.nogroddb.tables.Transaction;
import burst.pool.migrator.nogroddb.tables.TransactionRecipient;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in nogrod_vlp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>nogrod_vlp.account</code>.
     */
    public static final Account ACCOUNT = burst.pool.migrator.nogroddb.tables.Account.ACCOUNT;

    /**
     * The table <code>nogrod_vlp.block</code>.
     */
    public static final Block BLOCK = burst.pool.migrator.nogroddb.tables.Block.BLOCK;

    /**
     * The table <code>nogrod_vlp.miner</code>.
     */
    public static final Miner MINER = burst.pool.migrator.nogroddb.tables.Miner.MINER;

    /**
     * The table <code>nogrod_vlp.nonce_submission</code>.
     */
    public static final NonceSubmission NONCE_SUBMISSION = burst.pool.migrator.nogroddb.tables.NonceSubmission.NONCE_SUBMISSION;

    /**
     * The table <code>nogrod_vlp.schema_migrations</code>.
     */
    public static final SchemaMigrations SCHEMA_MIGRATIONS = burst.pool.migrator.nogroddb.tables.SchemaMigrations.SCHEMA_MIGRATIONS;

    /**
     * The table <code>nogrod_vlp.transaction</code>.
     */
    public static final Transaction TRANSACTION = burst.pool.migrator.nogroddb.tables.Transaction.TRANSACTION;

    /**
     * The table <code>nogrod_vlp.transaction_recipient</code>.
     */
    public static final TransactionRecipient TRANSACTION_RECIPIENT = burst.pool.migrator.nogroddb.tables.TransactionRecipient.TRANSACTION_RECIPIENT;
}
