/*
 * This file is generated by jOOQ.
 */
package burst.pool.migrator.nogroddb.information_schema.tables;


import burst.pool.migrator.nogroddb.information_schema.InformationSchema;
import burst.pool.migrator.nogroddb.information_schema.tables.records.UserStatisticsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserStatistics extends TableImpl<UserStatisticsRecord> {

    private static final long serialVersionUID = -1956892317;

    /**
     * The reference instance of <code>information_schema.USER_STATISTICS</code>
     */
    public static final UserStatistics USER_STATISTICS = new UserStatistics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserStatisticsRecord> getRecordType() {
        return UserStatisticsRecord.class;
    }

    /**
     * The column <code>information_schema.USER_STATISTICS.USER</code>.
     */
    public final TableField<UserStatisticsRecord, String> USER = createField("USER", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.TOTAL_CONNECTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Integer> TOTAL_CONNECTIONS = createField("TOTAL_CONNECTIONS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.CONCURRENT_CONNECTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Integer> CONCURRENT_CONNECTIONS = createField("CONCURRENT_CONNECTIONS", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.CONNECTED_TIME</code>.
     */
    public final TableField<UserStatisticsRecord, Integer> CONNECTED_TIME = createField("CONNECTED_TIME", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.BUSY_TIME</code>.
     */
    public final TableField<UserStatisticsRecord, Double> BUSY_TIME = createField("BUSY_TIME", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.CPU_TIME</code>.
     */
    public final TableField<UserStatisticsRecord, Double> CPU_TIME = createField("CPU_TIME", org.jooq.impl.SQLDataType.DOUBLE.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.BYTES_RECEIVED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> BYTES_RECEIVED = createField("BYTES_RECEIVED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.BYTES_SENT</code>.
     */
    public final TableField<UserStatisticsRecord, Long> BYTES_SENT = createField("BYTES_SENT", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.BINLOG_BYTES_WRITTEN</code>.
     */
    public final TableField<UserStatisticsRecord, Long> BINLOG_BYTES_WRITTEN = createField("BINLOG_BYTES_WRITTEN", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROWS_READ</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROWS_READ = createField("ROWS_READ", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROWS_SENT</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROWS_SENT = createField("ROWS_SENT", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROWS_DELETED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROWS_DELETED = createField("ROWS_DELETED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROWS_INSERTED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROWS_INSERTED = createField("ROWS_INSERTED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROWS_UPDATED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROWS_UPDATED = createField("ROWS_UPDATED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.SELECT_COMMANDS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> SELECT_COMMANDS = createField("SELECT_COMMANDS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.UPDATE_COMMANDS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> UPDATE_COMMANDS = createField("UPDATE_COMMANDS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.OTHER_COMMANDS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> OTHER_COMMANDS = createField("OTHER_COMMANDS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.COMMIT_TRANSACTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> COMMIT_TRANSACTIONS = createField("COMMIT_TRANSACTIONS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ROLLBACK_TRANSACTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ROLLBACK_TRANSACTIONS = createField("ROLLBACK_TRANSACTIONS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.DENIED_CONNECTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> DENIED_CONNECTIONS = createField("DENIED_CONNECTIONS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.LOST_CONNECTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, Long> LOST_CONNECTIONS = createField("LOST_CONNECTIONS", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.ACCESS_DENIED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> ACCESS_DENIED = createField("ACCESS_DENIED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.EMPTY_QUERIES</code>.
     */
    public final TableField<UserStatisticsRecord, Long> EMPTY_QUERIES = createField("EMPTY_QUERIES", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.TOTAL_SSL_CONNECTIONS</code>.
     */
    public final TableField<UserStatisticsRecord, ULong> TOTAL_SSL_CONNECTIONS = createField("TOTAL_SSL_CONNECTIONS", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column <code>information_schema.USER_STATISTICS.MAX_STATEMENT_TIME_EXCEEDED</code>.
     */
    public final TableField<UserStatisticsRecord, Long> MAX_STATEMENT_TIME_EXCEEDED = createField("MAX_STATEMENT_TIME_EXCEEDED", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * Create a <code>information_schema.USER_STATISTICS</code> table reference
     */
    public UserStatistics() {
        this(DSL.name("USER_STATISTICS"), null);
    }

    /**
     * Create an aliased <code>information_schema.USER_STATISTICS</code> table reference
     */
    public UserStatistics(String alias) {
        this(DSL.name(alias), USER_STATISTICS);
    }

    /**
     * Create an aliased <code>information_schema.USER_STATISTICS</code> table reference
     */
    public UserStatistics(Name alias) {
        this(alias, USER_STATISTICS);
    }

    private UserStatistics(Name alias, Table<UserStatisticsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserStatistics(Name alias, Table<UserStatisticsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserStatistics(Table<O> child, ForeignKey<O, UserStatisticsRecord> key) {
        super(child, key, USER_STATISTICS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatistics as(String alias) {
        return new UserStatistics(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserStatistics as(Name alias) {
        return new UserStatistics(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserStatistics rename(String name) {
        return new UserStatistics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserStatistics rename(Name name) {
        return new UserStatistics(name, null);
    }
}
