/*
 * This file is generated by jOOQ.
 */
package burst.pool.db.burstpool.tables.records;


import burst.pool.db.burstpool.tables.Minerdeadlines;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinerdeadlinesRecord extends UpdatableRecordImpl<MinerdeadlinesRecord> implements Record5<Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = -68760502;

    /**
     * Setter for <code>BURSTPOOL.MINERDEADLINES.DB_ID</code>.
     */
    public void setDbId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>BURSTPOOL.MINERDEADLINES.DB_ID</code>.
     */
    public Long getDbId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>BURSTPOOL.MINERDEADLINES.ACCOUNT_ID</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>BURSTPOOL.MINERDEADLINES.ACCOUNT_ID</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>BURSTPOOL.MINERDEADLINES.HEIGHT</code>.
     */
    public void setHeight(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>BURSTPOOL.MINERDEADLINES.HEIGHT</code>.
     */
    public Long getHeight() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>BURSTPOOL.MINERDEADLINES.DEADLINE</code>.
     */
    public void setDeadline(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>BURSTPOOL.MINERDEADLINES.DEADLINE</code>.
     */
    public Long getDeadline() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>BURSTPOOL.MINERDEADLINES.BASETARGET</code>.
     */
    public void setBasetarget(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>BURSTPOOL.MINERDEADLINES.BASETARGET</code>.
     */
    public Long getBasetarget() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Long, Long, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Minerdeadlines.MINERDEADLINES.DB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Minerdeadlines.MINERDEADLINES.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Minerdeadlines.MINERDEADLINES.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Minerdeadlines.MINERDEADLINES.DEADLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Minerdeadlines.MINERDEADLINES.BASETARGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getBasetarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getDbId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getBasetarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord value1(Long value) {
        setDbId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord value3(Long value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord value4(Long value) {
        setDeadline(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord value5(Long value) {
        setBasetarget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerdeadlinesRecord values(Long value1, Long value2, Long value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MinerdeadlinesRecord
     */
    public MinerdeadlinesRecord() {
        super(Minerdeadlines.MINERDEADLINES);
    }

    /**
     * Create a detached, initialised MinerdeadlinesRecord
     */
    public MinerdeadlinesRecord(Long dbId, Long accountId, Long height, Long deadline, Long basetarget) {
        super(Minerdeadlines.MINERDEADLINES);

        set(0, dbId);
        set(1, accountId);
        set(2, height);
        set(3, deadline);
        set(4, basetarget);
    }
}
